### ISSUE TITLE
N is not defined

### ISSUE THREAD

**Issue by Gandi24** [select2/select2#5053]
Newest version of library (4.0.4) caused all initializations of $(elem).select2(init) to raise a N is not defined error. Freezing the version to 4.0.3 seems to solve the issue.

**Comment by alexweissman** [comment]
What do you mean by `$(elem).select2(init)`?  Could you provide some more details?

**Comment by alexweissman** [comment]
I see that other people have upvoted this issue, but no one has provided any details.  What browser does this occur in?  What configuration options are being used when this occurs?  A jsbin would be very helpful.

**Comment by alexweissman** [comment]
Is [this commit](https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e#commitcomment-24593031) possibly the cause of this problem?

**Comment by jvlobo** [comment]
I'm not sure about @Gandi24 exact issue, but I'm having something similar.

I'm using select2 in Aurelia with jspm, and in my js file I required select2 like: 

`import select2 from 'select2';`

With version 4.0.3 every was fine, but after updating to 4.0.4, I'm getting this on Chrome console:

> $('.myselect').select2 is not a function
>     at a.formatGroupsChanged (app-build-37c1cfeb50.js:3)
>     at a.b [as selfSubscriber] (aurelia-3efb406cb3.js:19)
>     at a.BehaviorPropertyObserver.a.call (aurelia-3efb406cb3.js:19)
>     at a.Controller.a.bind (aurelia-3efb406cb3.js:19)
>     at a.View.a.bind (aurelia-3efb406cb3.js:18)
>     at a.Controller.a.bind (aurelia-3efb406cb3.js:19)
>     at a.Controller.a.automate (aurelia-3efb406cb3.js:19)
>     at h (aurelia-3efb406cb3.js:12)
>     at a.RouterView.a.swap (aurelia-3efb406cb3.js:12)
>     at aurelia-3efb406cb3.js:12
> a.ConsoleAppender.a.error @ aurelia-3efb406cb3.js:11
> (anonymous) @ aurelia-3efb406cb3.js:19
> F @ aurelia-3efb406cb3.js:12
> (anonymous) @ aurelia-3efb406cb3.js:13
> Promise resolved (async)
> (anonymous) @ aurelia-3efb406cb3.js:13
> Promise resolved (async)
> a.AppRouter.b._dequeueInstruction @ aurelia-3efb406cb3.js:13
> (anonymous) @ aurelia-3efb406cb3.js:13
> a.AppRouter.b._queueInstruction @ aurelia-3efb406cb3.js:13
> (anonymous) @ aurelia-3efb406cb3.js:13
> Promise resolved (async)
> a.AppRouter.b.loadUrl @ aurelia-3efb406cb3.js:13
> a.BrowserHistory.c._loadUrl @ aurelia-3efb406cb3.js:4
> a.BrowserHistory.c.navigate @ aurelia-3efb406cb3.js:4
> a.Router.a.navigate @ aurelia-3efb406cb3.js:13
> a.openSubRoute @ app-build-37c1cfeb50.js:17
> a.CallScope.b.evaluate @ aurelia-3efb406cb3.js:15
> a.Listener.a.callSource @ aurelia-3efb406cb3.js:17
> a.Listener.a.handleEvent @ aurelia-3efb406cb3.js:17
> ca @ aurelia-3efb406cb3.js:14

So, apparently, the problem comes with that commit you mention??

Cheers!

**Comment by IamBirgitte** [comment]
I have encountered the issue in both Chrome, Firefox and Safari.

As I did not encounter the issue on my local environment which had version 4.0.3, though our live environment had upgraded to 4.0.4 during a deploy last week. 
I tested with 4.0.4 on my local environment as well, considering there had been no change to our codebase for how we use select2, and got the same error. Rolling back to 4.0.3 has solved our issue.

I get the following error in my console:
```
Uncaught ReferenceError: N is not defined
    at D.apply (production.min.js?1506951467249092000:7)
    at new e (production.min.js?1506951467249092000:7)
    at new e (production.min.js?1506951467249092000:7)
    at HTMLSelectElement.<anonymous> (production.min.js?1506951467249092000:8)
    at Function.each (production.min.js?1506951467249092000:1)
    at ea.fn.init.each (production.min.js?1506951467249092000:1)
    at ea.fn.init.a.fn.select2 (production.min.js?1506951467249092000:8)
    at HTMLSelectElement.<anonymous> (production.min.js?1506951467249092000:12)
    at Function.each (production.min.js?1506951467249092000:1)
    at ea.fn.init.each (production.min.js?1506951467249092000:1)
```
Hope this helps

**Comment by alexweissman** [comment]
@IamBirgitte are you also using `require` or some similar module system?  Can you try swapping out the minified version for the unminified version, so we can get a more precise error message?

**Comment by IamBirgitte** [comment]
@alexweissman We're not using require, but we're using grunt to concat our js files.

Currently we minify our code, but also using your minified js file. I just swapped our your minified version with theunminified version, though instead of better error messages I get none. Now our site is working fine with 4.0.4, simply by not using the minified version.
Which is a little bit puzzling to me.

**Comment by alexweissman** [comment]
@IamBirgitte I am confused by "Currently we minify our code, but also using your minified js file".  So, which of the following work for you?

- [ ] our unminified distribution of 4.0.4
- [ ] our minified distribution of 4.0.4
- [ ] your minified version of 4.0.4

Sorry, your language was not very clear on this.

**Comment by IamBirgitte** [comment]
Sorry for the confusion @alexweissman 
The unminified version of 4.0.4 is working for us.

**Comment by IamBirgitte** [comment]
So I have found the issue I've had, which is basically me being an idiot.  :disappointed_relieved:
Adding the minified file to a file which I am later minifying was causing our issues, though I am not certain if that's the same issue OP has got due to lack of information on his part.
Sorry about that @alexweissman, and thank you for your help!

**Comment by rickclare** [comment]
@jvlobo We had the same issue as you with v4.0.4 (we used Brunch for our builds, which by default uses CommonJS internally)

The solution that worked for us was as follows (add a line after the `import` statement)

```js
import select2 from "select2";
select2(window, jQuery);
```

This solution was suggested by @tangshuang in the following commit comment: https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e#commitcomment-24593031

Hope that helps you too.

**Comment by alexweissman** [comment]
@IamBirgitte thanks for the clarification!  I am still confused though, because minification is supposed to be an idempotent operation (that is, minifying an already minified file should return the same result).  What are you using to minify your code?

**Comment by alexweissman** [comment]
@rickclare since you're using CommonJS, do you have any suggestions for how to patch this issue in Select2 directly?  By the way, I've set up a [Select2 chat room](https://chat.userfrosting.com/channel/select2) on my chat server where we can communicate in real-time, if anyone is interested.

**Comment by alexweissman** [comment]
@jvlobo @rickclare have you seen #4617?  Seems like it might be a related issue.

**Comment by IamBirgitte** [comment]
@alexweissman I was under the same impression, especially as there was no issues with the previous version or other files.

We're using `grunt-contrib-uglify`

**Comment by alexweissman** [comment]
Ok, this is the [same package that Select2 uses](https://github.com/select2/select2/blob/master/Gruntfile.js#L334), actually.

@IamBirgitte It might be worth trying to isolate this problem, if you have a chance.  Can you try passing the raw distribution of `select2.js` through `grunt-contrib-uglify` **twice**, and see if the results are the same before and after the second pass?  If not, it might be an issue with UglifyJS.

**Comment by geekabhinav** [comment]
Same issue here. Updating to 4.0.4 broke the pages in my application which used select2, only in production (after minifying). It was working fine earlier on 4.0.3. 

How I fixed it in 4.0.4:

- Earlier I was pointing to dist/select2.min.js in requirejs
- Changed it to dist/select2

Using Grunt, RequireJS

**Comment by alexweissman** [comment]
@geekabhinav this sounds kind of like @IamBirgitte's issue.  Is there maybe just a problem with the minified distribution code?

**Comment by geekabhinav** [comment]
@alexweissman Not sure, because using jshint does not throw any errors, only warnings

**Comment by Sureiya** [comment]
I'm using browserify and babel, and encountered this issue as well. It was definitely caused by https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e

I was able to get around it by changing
```
require('select2');
```
to
```
var select2 = require('select2');
select2($);
```

**Comment by feitla** [comment]
I can confirm this is occurring in 4.0.4 and above. Jquery is undefined. 4.0.3 does not have this issue

**Comment by PeterA** [comment]
We are having the same issue. If we run `gulp --production` with Select2 Version 4.0.4 or 4.0.5 the Select2 functionality breaks and Chrome's console shows: `Uncaught ReferenceError: R is not defined.` Downgrading to version 4.0.3 or changing our gulpfile.js to reference `select2/dist/js/select2.full.js` instead of `select2/dist/js/select2.full.min.js` resolves the issue for us.

**Comment by alexweissman** [comment]
So, can you confirm that there is a problem with the way `/js/select2.full.js` is being minified?

**Comment by alexweissman** [comment]
Thanks for providing this in-depth analysis!  It sounds like something is probably going wrong with `grunt-contrib-uglify` when it tries to minify `select2.full.js`, so that the minified content creates errors even though browsers are able to handle the unminified version just fine.

I've seen this happen before in CSS actually, back when I used to use the YUI compressor.  I had some malformed CSS which browsers could interpret just fine in unminified form, but then caused errors when it was minified.

FYI, instead of attaching zip files with code, in the future it would be better if you simply posted a link to a [gist](https://gist.github.com) 😄

**Comment by alexweissman** [comment]
For reference, here is the full diff between versions 4.0.3 and 4.0.4: https://github.com/select2/select2/compare/566c7846fbf8c3b7674346f26d0ee872c0a77629...16f6b10628f9000918708cef9b3da615119cf6d6

**Comment by alexweissman** [comment]
@PeterA something that would really help, is if you could run the double-minified file that is causing this error back through a [Javascript beautifier](http://jsbeautifier.org/).  Then, put this beautified file back into your project and identify the line that is triggering the error.  This will let us trace the error back to the original source code.

**Comment by kesha-antonov** [comment]
Thanks @Sureiya 
worked!

**Comment by orditeck** [comment]
I had the same issue. 

It was coming this line:

```
options = $.extend(true, {}, this.defaults, options);
```

$ was not defined on versions >= 4.0.4.

Going back to 4.0.3 fixed the issue for me.

**Comment by SpikeShape** [comment]
@geekabhinav this just saved me after looking around for about 2 hours. Thank you!

Using the .min.js file caused the `N is not defined`  error but using the unminified version resolved it. Not sure what is going on there.

**Comment by yunai39** [comment]
> @geekabhinav this just saved me after looking around for about 2 hours. Thank you!
> 
> Using the .min.js file caused the `N is not defined` error but using the unminified version resolved it. Not sure what is going on there.

Same, had the error when using the min but no error when using the unminified version.
