### ISSUE TITLE
Support for jQuery 4

### ISSUE THREAD

**Issue by marcellov7** [select2/select2#6298]
Hi,

I'm an enthusiastic user of Select2 and greatly appreciate its features and effectiveness. However, with the recent announcement of the release of jQuery 4 and its promises to significantly improve library performance, I was wondering if there are plans to ensure Select2 compatibility with this new version of jQuery.
https://blog.jquery.com/2024/02/06/jquery-4-0-0-beta/

I understand that Select2 relies on jQuery and that the upgrade may take time and effort, but considering the potential benefits in terms of performance and future compatibility, it would be extremely helpful for the community to know if there is a commitment to making Select2 compatible with jQuery 4.

Is there a roadmap or defined plan for this? Additionally, if there are opportunities to contribute or support this effort, I would be happy to provide my assistance.

Thank you

**Comment by jamesleesaunders** [comment]
One first observation testing select2 with jQuery4 is:
- jQuery.isArray is deprecated; use Array.isArray

jQuery: 3.7.1
select2: 4.1.0-rc.0
django-select2: 8.1.2

```
        if (self.options.get('debug') && window.console && console.error) {
          // Check to make sure that the response included a `results` key.
          if (!results || !results.results || !$.isArray(results.results)) {             <--- HERE
            console.error(
              'Select2: The AJAX results did not return an array in the ' +
              '`results` key of the response.'
            );
          }
        }
```

```
jquery.js:1 JQMIGRATE: Migrate is installed with logging active, version 3.4.1
jquery.js:1 jQuery Version 3.7.1 Loaded
jquery.js:1 JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray
a @ jquery.js:1
t.<computed> @ jquery.js:1
n._resolveLanguage @ select2.full.min.js:2
n.applyFromElement @ select2.full.min.js:2
e @ select2.full.min.js:2
d @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:2
each @ jquery.js:1
each @ jquery.js:1
r.fn.select2 @ select2.full.min.js:2
initHeavy @ django_select2.js:48
(anonymous) @ django_select2.js:56
each @ jquery.js:1
$.fn.djangoSelect2 @ django_select2.js:53
(anonymous) @ django_select2.js:71
l @ jquery.js:1
c @ jquery.js:1
setTimeout (async)
(anonymous) @ jquery.js:1
u @ jquery.js:1
fireWith @ jquery.js:1
fire @ jquery.js:1
u @ jquery.js:1
fireWith @ jquery.js:1
ready @ jquery.js:1
Z @ jquery.js:1
jquery.js:1 console.trace
a @ jquery.js:1
t.<computed> @ jquery.js:1
n._resolveLanguage @ select2.full.min.js:2
n.applyFromElement @ select2.full.min.js:2
e @ select2.full.min.js:2
d @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:2
each @ jquery.js:1
each @ jquery.js:1
r.fn.select2 @ select2.full.min.js:2
initHeavy @ django_select2.js:48
(anonymous) @ django_select2.js:56
each @ jquery.js:1
$.fn.djangoSelect2 @ django_select2.js:53
(anonymous) @ django_select2.js:71
l @ jquery.js:1
c @ jquery.js:1
setTimeout (async)
(anonymous) @ jquery.js:1
u @ jquery.js:1
fireWith @ jquery.js:1
fire @ jquery.js:1
u @ jquery.js:1
fireWith @ jquery.js:1
ready @ jquery.js:1
Z @ jquery.js:1
```

**Comment by jamesleesaunders** [comment]
Actually, stand down on the `isArray` comment above. This looks to be an issue with django-select2 including an older version of select2 (4.0.13). It looks like you have already replaced all instances of $isArray in the latest (4.1.0-rc.0).

I have raised issue over on the django-select2 side: https://github.com/codingjoe/django-select2/issues/267

**Comment by jamesleesaunders** [comment]
Also see https://github.com/select2/select2/issues/6253

**Comment by marcellov7** [comment]
In general, it seems to work, but a more in-depth analysis would be needed.

**Comment by jonblatho** [comment]
I'm sure I don't speak for everyone, and I'm not sure how much effort the jQuery 4 migration will require, but personally as a user, if substantial effort is going to be spent on a migration I'd much rather it be spent on removing the jQuery dependency altogether (#6196).

**Comment by marcellov7** [comment]
> I'm sure I don't speak for everyone, and I'm not sure how much effort the jQuery 4 migration will require, but personally as a user, if substantial effort is going to be spent on a migration I'd much rather it be spent on removing the jQuery dependency altogether (#6196).

I don't think it's strictly necessary given the nature of the plugin, there are several alternatives out there that work very well without jQuery. Also because the time it would take you to rewrite things without jQuery (if ever a Select2 without jQuery will ever be released) you have already made the switch to another one without jQuery.
Furthermore, with ChatGPT you would quickly switch to an alternative. 🤣

jQuery 4 brings notable improvements and since Select2 is incorporated into this, it is in my opinion important to do a check to determine if any problems with jQuery v4 come out, but it seems to work very well for the moment.

I opened the issue only to encourage those who are more familiar than me to carry out a more in-depth check based on the deprecate elements in jQuery 4.

**Comment by Nedlinin** [comment]
@marcellov7 : According to jQuery, camelCase no longer exists: https://blog.jquery.com/2024/02/06/jquery-4-0-0-beta/

It is used here: https://github.com/select2/select2/blob/ed1761a7f6e88c8c5d305e7022fecb264d2271ab/src/js/select2/defaults.js#L424

Not sure what else might be broken but this one at least stood out to me as broken on one of my sites.

**Comment by marcellov7** [comment]
[https://github.com/marcellov7/select2/tree/support-jQuery-4.0.0-beta](https://github.com/marcellov7/select2/tree/support-jQuery-4.0.0-beta)
I should have sorted everything out, it seems OK in the testing part too.
Please review and pull request if necessary.

Thanks

**Comment by JCCChris** [comment]
Seems like it would be possible to inject the missing functions back into jQuery and use the native functions and add the extra bit that jQuery added such as null handling.

Anyone see any problems with the following code to add the missing functions back in: (after jQuery but before select2)

jQuery.isArray = Array.isArray || function (value) {
    return Object.prototype.toString.call(value) === '[object Array]';
};
jQuery.trim = function (text) {
    return text == null ? "" : text.trim();
};
I didn't need to replace camelCase() for some reason, but that might need to be filled in too.

**Comment by jamesleesaunders** [comment]
Would the effort be best simply refactoring the bits of code (if any) which uses these?

Otherwise if you were to be running the jQuery migrate add-on it would it still be complaining that these functions are deprecated?   https://github.com/jquery/jquery-migrate 

That said, granted it would still work.

**Comment by JCCChris** [comment]
I would love it if this project would refactor to eliminate deprecated calls.

**Comment by sabas** [comment]
see #6196

**Comment by chrfritsch** [comment]
Hi, as the select2 maintainer of the Drupal integration, I would like to see this getting landed. The upcoming Drupal 11 release will drop jQuery 3 and use jQuery 4 instead. 
So to provide a smooth migration for all Drupal users, that are using the select2 module(over 20k installations), from D10 to D11, getting this done is mandatory.

@kevin-brown Could you please provide a timeframe for this? I am also happy to help if necessary.

**Comment by jayaddison** [comment]
@marcellov7 there's a small bug with the [`camelCase` implementation](https://github.com/marcellov7/select2/blob/cddedf3defe8dbf47ca3f75dedd27e0699b09068/src/js/select2/defaults.js#L424) in your branch, and it affects the way that `select2` handles [nested option names](https://select2.org/configuration/defaults#nested-options):

**Expected**
```javascript
var key = 'ajax--cache';
$.camelCase(key);
"ajax-Cache" 
```

**Actual**
```javascript
var key = 'ajax--cache';
(str => str.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase()))(key);
"ajaxCache" 
```

There's an approach in `select2` in `src/select2/options.js` that we could re-use as a fix: https://github.com/select2/select2/blob/45f2b83ceed5231afa7b3d5b12b58ad335edd82e/src/js/select2/options.js#L99-L100

**Suggested**
```javascript
function upperCaseLetter(_, letter) {
  return letter.toUpperCase();
}
var key = 'ajax--cache';
key.replace(/-([a-z])/g, upperCaseLetter);
"ajax-Cache" 
```

Edit: add JavaScript syntax highlighting to suggestion snippet.

**Comment by marcellov7** [comment]
> @marcellov7 there's a small bug with the [`camelCase` implementation](https://github.com/marcellov7/select2/blob/cddedf3defe8dbf47ca3f75dedd27e0699b09068/src/js/select2/defaults.js#L424) in your branch, and it affects the way that `select2` handles [nested option names](https://select2.org/configuration/defaults#nested-options):
> 
> **Expected**
> 
> ```js
> var key = 'ajax--cache';
> $.camelCase(key);
> "ajax-Cache" 
> ```
> 
> **Actual**
> 
> ```js
> var key = 'ajax--cache';
> (str => str.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase()))(key);
> "ajaxCache" 
> ```
> 
> There's an approach in `select2` in `src/select2/options.js` that we could re-use as a fix:
> 
> https://github.com/select2/select2/blob/45f2b83ceed5231afa7b3d5b12b58ad335edd82e/src/js/select2/options.js#L99-L100
> 
> **Suggested**
> 
> ```js
> function upperCaseLetter(_, letter) {
>   return letter.toUpperCase();
> }
> var key = 'ajax--cache';
> key.replace(/-([a-z])/g, upperCaseLetter);
> "ajax-Cache" 
> ```
> 
> Edit: add JavaScript syntax highlighting to suggestion snippet.

Thanks @jayaddison

**Comment by mmarras** [comment]
Jquery4 has been released 10 days ago.

~Now using select2 4.0.13 with django6.0.1 and djago-select2 8.4.8 breaks still with reference to remove jQuery.isArray function~

> ~jquery.min.js:2  Uncaught TypeError: c.isArray is not a function
    at n._resolveLanguage (select2.full.min.js:2:56289)
    at n.applyFromElement (select2.full.min.js:2:56041)
    at new e (select2.full.min.js:2:57173)
    at new d (select2.full.min.js:2:59401)
    at HTMLSelectElement.<anonymous> (select2.full.min.js:2:77253)
    at T.each (jquery.min.js:2:2869)
    at T.fn.init.each (jquery.min.js:2:1379)
    at r.fn.select2 (select2.full.min.js:2:77213)
    at initHeavy (django_select2.js:55:14)
    at HTMLSelectElement.<anonymous> (django_select2.js:63:9)~

Nevermind, works with 4.1.0rc.

**Comment by pa-nathan** [comment]
Ok, so it should work with 4.1.0rc if I understand correctly? Will this version be released some day or has this library been abandoned (no release since 6 years)?

**Comment by kevin-brown** [comment]
Handled in https://github.com/select2/select2/pull/6403
