### ISSUE TITLE
select all / select none header

### ISSUE THREAD

**Issue by ethanj** [select2/select2#195]
it would be great to have this type of functionality added...

see
http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/#headers

**Comment by kevin-brown** [comment]
This can be done by overriding the `dropdownAdapter` and decorating the `render` method l[ike we do for the search](https://github.com/select2/select2/blob/473267404aeee8c4380ac2ba4558016872236398/src/js/select2/dropdown/search.js).

We've decided to not include the proposed `formatHeader` and `formatFooter` methods because of this.

**Comment by ChetnaN** [comment]
Solution given by MortadaAK and sieppl are working fine in Firefox, but not working on Chrome.
Changed "Keypress" to "Keydown" for Chrome, now its calling the event, but still the functionality not working.
Please help.

**Comment by kevin-brown** [comment]
I finally had some time to get around to creating a demo with the decorator that adds a "Select all" button to the dropdown.

http://jsbin.com/seqonozasu/1/edit?html,js,output

**Comment by shorif2000** [comment]
this should be added to the docs, very useful feature and i am sure a lot of people need this. also some easy to find demo's, I have been searching a long time before i came across this thread

**Comment by shorif2000** [comment]
How can i use this without using requires amd loader?

**Comment by bkdotcom** [comment]
@shorif2000 

the amd loader is included with select2

what's not obvious is how to make the adapter reusable

	/*
          Define the adapter so that it's reusable
	*/    	   
	$.fn.select2.amd.define('select2/selectAllAdapter', [
		'select2/utils',
		'select2/dropdown',
		'select2/dropdown/attachBody'
	], function (Utils, Dropdown, AttachBody) {

		function SelectAll() { }
		SelectAll.prototype.render = function (decorated) {
			var self = this,
				$rendered = decorated.call(this),
				$selectAll = $(
					'<button class="btn btn-xs btn-default" type="button" style="margin-left:6px;"><i class="fa fa-check-square-o"></i> Select All</button>'
				),
				$unselectAll = $(
					'<button class="btn btn-xs btn-default" type="button" style="margin-left:6px;"><i class="fa fa-square-o"></i> Unselect All</button>'
				),
				$btnContainer = $('<div style="margin-top:3px;">').append($selectAll).append($unselectAll);
			$rendered.find('.select2-dropdown').prepend($btnContainer);
			$selectAll.on('click', function (e) {
				var $results = $rendered.find('.select2-results__option[aria-selected=false]');
				$results.each(function () {
					self.trigger('select', {
						data: $(this).data('data')
					});
				});
				self.trigger('close');
			});
			$unselectAll.on('click', function (e) {
				var $results = $rendered.find('.select2-results__option[aria-selected=true]');
				$results.each(function () {
					self.trigger('unselect', {
						data: $(this).data('data')
					});
				});
				self.trigger('close');
			});
			return $rendered;
		};

		return Utils.Decorate(
			Utils.Decorate(
				Dropdown,
				AttachBody
			),
			SelectAll
		);

	});

        /*
          adapter could have been defined elsewhere in a global includes script or whereever
          we can now use it elsewhere
        */
	$(function(){
		$("select").select2({
			placeholder: "Select Option(s)...",
			dropdownAdapter: $.fn.select2.amd.require('select2/selectAllAdapter')
		});
	});

**Comment by Jaded-Design** [comment]
Would like to add that this isn't really a good solution if you have more than a handful of options to select. During testing we found that over a certain threshold this script will actually fully lock up your browser. 

Definitely not ideal. 

Would love to see this implemented as a full feature and optimized to work with the rest of the select2 library.

**Comment by DevXen** [comment]
My question would be.  If you manually check to that threshold, does your
browser still lock up? My guess is that it's a ram issue.

**Comment by arborrow** [comment]
I really cannot find a quick way to select all of the options despite https://github.com/select2/select2/issues/195#issuecomment-7617521 - the list stays opens and that is helpful but it immediately goes back to the already selected option and then I have to scroll down to the next unselected option. There are several issues related to this and am curious what resolution folks have used. Peace - Anthony

**Comment by huykon** [comment]
I tried @kevin-brown code and this is working perfect for me but I have issue is I am using select ajax. how I can sellect all product without enter anyone a character to input ? Please help me. thanks

**Comment by mkoch42** [comment]
@bkdotcom solution worked great.  I wonder though is there a way to not show the select all button either
a) until X amount of keys are typed (eg 3 characters, not just 1)
or better
b) based on the number of results... eg if over 100 results don't allow select all, make the user drill it down to lower (say 50) results befoer showing the select all (or clear all) buttons. 

We still find that when there are 100s-1000s of entries the select all or clear all buttons lock the browser so limiting the buttons to only show up when x amounts.

Any help would be much appreciated.

Thanks
Matt

**Comment by ofry** [comment]
Why this issue was closed?

**Comment by bkdotcom** [comment]
somewhat related...  is it possible to change the "value(s)" that are displayed for a multi-select?
somewhat similar to [templateSelection](https://select2.github.io/options.html#templateSelection).

If all options are selected, I'd like to display "all selected"   vs listing each option comma-separated

**Comment by jan-lugfl** [comment]
@arborrow : I actually has the same issue with the dropdown not closing for single selects, the additional code below solves that problem.
It leaves the dropdown open for multiple selects to keep it convenient..

```
    SelectAll.prototype.bind = function (decorated, container, $container) {
		var scope = this;
		decorated.call(this, container, $container);
		if(!this.$element.prop("multiple"))
			container.on('select', function (evt) {
				scope.trigger('close');
			});
	};
```

**Comment by EricJZell** [comment]
@mkoch42 Here I have added feature to disable the `Select All` button unless there are less than 25 results (of course that number can be updated as desired):
https://jsfiddle.net/hula_zell/50v60cm6/1/

**Comment by mkoch42** [comment]
@EricJZell Awesome! This works great. Thanks so much. Since you have such a great understanding of these adapters and select2, I am wondering if you can help with the ajax adapter and something I am trying to accomplish...I started a thread about it elsewhere on this github so will find it now and comment there with your name so that we can see if it is in your wheelhouse!  Thanks again.

**Comment by alexweissman** [comment]
@mkoch42 there is also a blog post about writing custom adapters here: https://bojanv91.github.io/posts/2017/10/extending-select2-with-adapters-and-decorators

I have asked the author to consider contributing them to the official documentation.

**Comment by mkoch42** [comment]
@EricJZell If I wanted to pass the maximum select all number (currently hard coded as 25) as a variable, where would I add the variable and how would I pass it.  I am a pretty great developer (CF/js/php/etc) but am not figuring this out with my first attempts so if you don’t mind altering the jsfiddle to to allow for passing the number as an argument that would be hugely helpful!

**Comment by Jay54520** [comment]
@bkdotcom 
The browser can't respond when there're 600 options if I click `Select All`

**Comment by alexweissman** [comment]
Seems like, even if this won't be added as a core feature, we could provide a "recipe" in the docs with one of the suggested solutions.

**Comment by Jay54520** [comment]
@bkdotcom @shorif2000 
There is a error in the console `No select2/compat/inputData`, but I don't see it in http://jsbin.com/seqonozasu/1/edit?html,js,console,output 

Still has the error even if I replace my select2.js to `<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.js"></script>`

**Comment by F-Tahir** [comment]
Wondering if anybody has managed to get @kevin-brown or @bkdotcom's solution working in the latest version of Select2? I've tried to no avail. Get this error in the console:

`select2.min.js:1 Uncaught TypeError: Cannot set property 'selected' of undefined
    at d.select (select2.min.js:1)
    at e.<anonymous> (select2.min.js:1)
    at e.d.invoke (select2.min.js:1)
    at e.d.trigger (select2.min.js:1)
    at e.trigger (select2.min.js:1)
    at d.<anonymous> (select2.min.js:1)
    at d.invoke (select2.min.js:1)
    at d.trigger (select2.min.js:1)
    at HTMLLIElement.<anonymous> (pen.js:29)
    at Function.each (jquery.min.js:2)`

**Comment by mkoch42** [comment]
@EricJZell solution works great.  His jsfiddle is what I used to integrate into my code:
https://jsfiddle.net/hula_zell/50v60cm6/1/

**Comment by QuentinBontemps** [comment]
@EricJZell solution works fine !

I added the none option : 

```javascript 
$.fn.select2.amd.require([
                'select2/utils',
                'select2/dropdown',
                'select2/dropdown/attachBody'
            ], function (Utils, Dropdown, AttachBody) {
                function SelectAll() {
                }

                SelectAll.prototype.render = function (decorated) {
                    var $rendered = decorated.call(this);
                    var self = this;

                    var $selectAll = $('<a/>').addClass('btn btn-info').text('Select all');
                    var $selectNone = $('<a/>').addClass('btn btn-info').text('None');

                    var checkOptionsCount = function () {
                        var count = $('.select2-results__option').length;
                        $selectAll.prop('disabled', count > 25);
                    };

                    var $container = $('.select2-container');
                    $container.bind('keyup click', checkOptionsCount);

                    var $dropdown = $rendered.find('.select2-dropdown');

                    $dropdown.prepend($selectNone);
                    $dropdown.prepend($selectAll);

                    $selectAll.on('click', function (e) {
                        var $results = $rendered.find('.select2-results__option[aria-selected=false]');

                        // Get all results that aren't selected
                        $results.each(function () {
                            var $result = $(this);

                            // Get the data object for it
                            var data = $result.data('data');

                            // Trigger the select event
                            self.trigger('select', {
                                data: data
                            });
                        });

                        self.trigger('close');
                    });

                    $selectNone.on('click', function (e) {
                        // Trigger value changed with null value
                        self.$element.val(null);
                        self.$element.trigger('change');
                        self.trigger('close');
                    });

                    return $rendered;
                };

                $("#roles").select2({
                    dropdownAdapter: Utils.Decorate(
                        Utils.Decorate(
                            Dropdown,
                            AttachBody
                        ),
                        SelectAll
                    )
                });
            });
```

**Comment by EricJZell** [comment]
Here is an updated jsfiddle implementing @bkdotcom solution for an easily re-usable dropdownAdaptor, with the SELECT_ALL_LIMIT
https://jsfiddle.net/hula_zell/50v60cm6/

The question becomes: What should you set your SELECT_ALL_LIMIT to? 
In the jsfiddle I've set it at 25, which is very conservative.  You will be ok setting the limit higher, although at some unknown point, it will lock up your browser!

**Comment by arthipesa** [comment]
Um, the sample was about getting select all / none from an existing options, what about the ajax / remote solution for this? I meant, when the page is reloaded the options aren't there yet, until someone is searching, but what if when we need to have it already select all the options when the page reloaded in the first time?

**Comment by meddario** [comment]
Hi,
is there any way to get the data for remote (ajax) results?
This part:
```javascript
      // Get all results that aren't selected
      $results.each(function() {
        var $result = $(this);

        // Get the data object for it
        var data = $result.data('data');

        // Trigger the select event
        self.trigger('select', {
          data: data
        });
      });
```

doesn't work, the `$result.data('data')` just returns `undefined`, calling `$result.data()` returns for example `{ select2Id: 13 }`. Is there a way to set the actual results from this information? Thanks!

**Comment by puneetnsit** [comment]
Hi @bkdotcom , I tried with your adaptor to put select all option but i have around 1000 entries for which browser gets locked up. Is there any better approach which can improve the performance

**Comment by mzabuawala** [comment]
Select2 With the latest version of Select2 (Select2 4.0.6-rc.1), $result.data('data') is returning undefined in 'select2/selectAllAdapter' when I click on 'Select All'.

Can anybody help?

**Comment by mzabuawala** [comment]
@meddario Did you find any solution?
I am facing the same issue as yours. data() returns undefined.

Thanks in advance.

**Comment by pedrofurtado** [comment]
"Select all" is hard to make when working with remote ajax data, because we dont have control about how many records has and what the JSON structure (for example) it has.There are some workarounds with that, but depends on application where select2 is used.

**Comment by raahhosting** [comment]
> @EricJZell solution works fine !
> 
> I added the none option :
> 
> ```js
> $.fn.select2.amd.require([
>                 'select2/utils',
>                 'select2/dropdown',
>                 'select2/dropdown/attachBody'
>             ], function (Utils, Dropdown, AttachBody) {
>                 function SelectAll() {
>                 }
> 
>                 SelectAll.prototype.render = function (decorated) {
>                     var $rendered = decorated.call(this);
>                     var self = this;
> 
>                     var $selectAll = $('<a/>').addClass('btn btn-info').text('Select all');
>                     var $selectNone = $('<a/>').addClass('btn btn-info').text('None');
> 
>                     var checkOptionsCount = function () {
>                         var count = $('.select2-results__option').length;
>                         $selectAll.prop('disabled', count > 25);
>                     };
> 
>                     var $container = $('.select2-container');
>                     $container.bind('keyup click', checkOptionsCount);
> 
>                     var $dropdown = $rendered.find('.select2-dropdown');
> 
>                     $dropdown.prepend($selectNone);
>                     $dropdown.prepend($selectAll);
> 
>                     $selectAll.on('click', function (e) {
>                         var $results = $rendered.find('.select2-results__option[aria-selected=false]');
> 
>                         // Get all results that aren't selected
>                         $results.each(function () {
>                             var $result = $(this);
> 
>                             // Get the data object for it
>                             var data = $result.data('data');
> 
>                             // Trigger the select event
>                             self.trigger('select', {
>                                 data: data
>                             });
>                         });
> 
>                         self.trigger('close');
>                     });
> 
>                     $selectNone.on('click', function (e) {
>                         // Trigger value changed with null value
>                         self.$element.val(null);
>                         self.$element.trigger('change');
>                         self.trigger('close');
>                     });
> 
>                     return $rendered;
>                 };
> 
>                 $("#roles").select2({
>                     dropdownAdapter: Utils.Decorate(
>                         Utils.Decorate(
>                             Dropdown,
>                             AttachBody
>                         ),
>                         SelectAll
>                     )
>                 });
>             });
> ```

On click on select all, nothing happens. Can I please get help

**Comment by MaryLamps** [comment]
> @EricJZell solution works fine !
> 
> I added the none option :
> 
> ```js
> $.fn.select2.amd.require([
>                 'select2/utils',
>                 'select2/dropdown',
>                 'select2/dropdown/attachBody'
>             ], function (Utils, Dropdown, AttachBody) {
>                 function SelectAll() {
>                 }
> 
>                 SelectAll.prototype.render = function (decorated) {
>                     var $rendered = decorated.call(this);
>                     var self = this;
> 
>                     var $selectAll = $('<a/>').addClass('btn btn-info').text('Select all');
>                     var $selectNone = $('<a/>').addClass('btn btn-info').text('None');
> 
>                     var checkOptionsCount = function () {
>                         var count = $('.select2-results__option').length;
>                         $selectAll.prop('disabled', count > 25);
>                     };
> 
>                     var $container = $('.select2-container');
>                     $container.bind('keyup click', checkOptionsCount);
> 
>                     var $dropdown = $rendered.find('.select2-dropdown');
> 
>                     $dropdown.prepend($selectNone);
>                     $dropdown.prepend($selectAll);
> 
>                     $selectAll.on('click', function (e) {
>                         var $results = $rendered.find('.select2-results__option[aria-selected=false]');
> 
>                         // Get all results that aren't selected
>                         $results.each(function () {
>                             var $result = $(this);
> 
>                             // Get the data object for it
>                             var data = $result.data('data');
> 
>                             // Trigger the select event
>                             self.trigger('select', {
>                                 data: data
>                             });
>                         });
> 
>                         self.trigger('close');
>                     });
> 
>                     $selectNone.on('click', function (e) {
>                         // Trigger value changed with null value
>                         self.$element.val(null);
>                         self.$element.trigger('change');
>                         self.trigger('close');
>                     });
> 
>                     return $rendered;
>                 };
> 
>                 $("#roles").select2({
>                     dropdownAdapter: Utils.Decorate(
>                         Utils.Decorate(
>                             Dropdown,
>                             AttachBody
>                         ),
>                         SelectAll
>                     )
>                 });
>             });
> ```

Can I please get help with this code, nothing happens when I click the select all button

**Comment by LukasLuMueller** [comment]
doesn't work for me.
still not solved imo.

**Comment by gsellitto** [comment]
> Wondering if anybody has managed to get @kevin-brown or @bkdotcom's solution working in the latest version of Select2? I've tried to no avail. Get this error in the console:
> 
> `
> select2.min.js:1 Uncaught TypeError: Cannot set property 'selected' of undefined
> 
> ```
> at d.select (select2.min.js:1)
> 
> at e.<anonymous> (select2.min.js:1)
> 
> at e.d.invoke (select2.min.js:1)
> 
> at e.d.trigger (select2.min.js:1)
> 
> at e.trigger (select2.min.js:1)
> 
> at d.<anonymous> (select2.min.js:1)
> 
> at d.invoke (select2.min.js:1)
> 
> at d.trigger (select2.min.js:1)
> 
> at HTMLLIElement.<anonymous> (pen.js:29)
> 
> at Function.each (jquery.min.js:2
> ```
> )`

Replace the rows:
      $result=$(this);
       var data = $result.data('select2-id');

with:
var data = Utils.GetData(this, 'data');

bye

**Comment by morrow95** [comment]
None of the linked examples here work - anyone have this working with the latest 4.0.8?

**Comment by AlainEdwards** [comment]
If anyone was looking for an alternative approach, I wrote the following:

`$(".select2-selection__rendered").keydown(function(event){
                if (event.ctrlKey || event.metaKey) {
                    if (event.shiftKey && event.which == 65){ //Ctr+Shift+A or Cmd+Shift+A
                        $(".select2-results__option").trigger('mouseup');
                    } 
                }
            });`

**Comment by rajesh-smartwebtech** [comment]
Hello  @ethanj  
Link not found 
http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/#headers

**Comment by ethanj** [comment]
lol.. amusing that you sent me this link after 5 years :)
if only we had access to a global Oracle of all information that we could ask where it moved to... oh wait... https://www.google.com/search?q=jquery-ui-multiselect-widget ...  https://ehynds.github.io/jquery-ui-multiselect-widget/

**Comment by almtorres** [comment]
I updated versions and not my selectAll button is not working? I was getting an select2.min.js:1 Uncaught TypeError: Cannot set property 'selected' of undefined, but then I suppressed it just to get another error Uncaught TypeError: $results.toLowerCase is not a function. Can anyone help I have been stuck on this for quite some time, thanks!
