### ISSUE TITLE
Select2 sortable multi select without using hidden input

### ISSUE THREAD

**Issue by ayublin** [select2/select2#1190]
Hi, I was in a condition that requires me to have my select2 multiple select to be sortable, but I found that I need to use hidden input instead of using normal multiple select to achieve that with current select2 features. Inspired by a plugin that is able to make jQuery chosen sortable, we've just pushed a little plugin to make select2 multiple select become sortable, hope someone may found this helpful https://github.com/vafour/select2-sortable.

**Comment by Daijobou** [comment]
Which one working with version 4.0? I use select2_sortable in version 3.5 and its working great, but this not working in version select2 4.0.x

**Comment by JacerOmri** [comment]
@martijn80 i loved your code and it works, how to implement events with this?

**Comment by clementhk** [comment]
Thanks @Daijobou , works.

**Comment by michaeljcoyne** [comment]
Wheres Demo? Doesn't work for me.

**Comment by wreardan** [comment]
Thanks a lot @Daijobou that works perfectly!  Saved me some headaches.

**Comment by wreardan** [comment]
@michaeljcoyne Did you change you calls from $('.select2').select() to $('.select2').select2_sortable() after adding the code above?

**Comment by Ardakilic** [comment]
@Daijobou Thank you, this worked flawlessly!

**Comment by Martijn-Schoenmaker** [comment]
@wreardan Where do I put the code? I get an error that ul.sortable is not a function.

**Comment by Ardakilic** [comment]
@Martijn-Schoenmaker You also need to include jQuery UI sortable to your project for this to run.

**Comment by Martijn-Schoenmaker** [comment]
@Ardakilic Ah thanks, pretty new to this hehe. I solved it by using: http://stackoverflow.com/questions/31431197/select2-how-to-prevent-tags-sorting. Works perfectly for me.

**Comment by haider07** [comment]
@alsahh can u plz help me if u have solve this problem of saving the new order after sorting?

**Comment by sagive** [comment]
JUST FYI... 
I think this line:
`var option = select.find('option[value="' + id + '"]')[0];`

Should go like this:
`var option = select.find(option[value="' + id + '"])[0];`

Than it should work for you guys...

**Comment by sagive** [comment]
BYW
this worked for me, **did some changes** as i discovered i have no data attr in the list:
`$(document).ready(function(){
	$.fn.extend({
		select2_sortable: function(){
			var select = $(this);
			$(select).select2({
				width: "100%",
				createTag: function(params) {
					return undefined;
				}
			});
			var ul = $(select).next(".select2-container").first("ul.select2-selection__rendered");
			ul.sortable({
				placeholder : "ui-state-highlight",
				forcePlaceholderSize: true,
				items       : "li:not(.select2-search__field)",
				tolerance   : "pointer",
				stop 		: function() {
					$( $(ul).find(".select2-selection__choice").get().reverse() ).each(function() {
						console.log(this);
						var title = $(this).attr("title");
						var option = $(select).find( "option:contains(" + title + ")" );
						console.log(option);
						$(select).prepend(option);
					});
				}
			});
		}
	});


	$(".select2posts").each(function(){
		$(this).select2_sortable();
	})
});`

**Comment by pista329** [comment]
Hey guys. Since this thread is a top one in search results, here are my two cents because non of the above worked for me. Hopefully someone finds this useful.

Uses `data-initial-sort` and hidden inputs.

```javascript
(function($){
  $.fn.extend({
      select2_sortable: function(opts){
          // Select2 tags as jQuery UI sortable 
          // - creates hidden inputs representing selected values
          // - sorts hidden inputs whenever sortable changes

          // Get essential variables
          var select = $(this);
          var select_name = $(select).attr('name');
          var initial_sort = $(select).attr('data-initial-sort').split(',');
          var form = $(select).closest("form");

          // Remove name to omit initial select from submitted values
          $(select).removeAttr('name');

          // Helper
          // - sorts hidden inputs according to sortable pills
          // - provide initial order if necessary
          function do_sort_inputs(order) {
            // Find, detach, sort and append all hidden inputs according to 
            // sortable pills DOM order
            var order = order || $(ul).find('.select2-selection__choice').map(function() {
              return $(this).data().data.id;
            }).get();
            
            $(form).find('input:hidden[name="' + select_name + '"]').detach().sort(function(a, b) {
              // Simple asc sorting based on sort index added before
              var a_ = order.indexOf($(a).attr('value'));
              var b_ = order.indexOf($(b).attr('value'));
              return a_ - b_;
            }).appendTo($(form));
          }

          // Helper
          // - sorts pills according to hidden inputs DOM order
          function do_sort_pills() {
            var order = $(form).find('input:hidden[name="' + select_name + '"]').map(function() {
              return $(this).attr('value');
            }).get();
            $(ul).find('.select2-selection__choice').detach().sort(function(a, b){
              var a_ = order.indexOf($(a).data().data.id);
              var b_ = order.indexOf($(b).data().data.id);
              return a_ - b_;
            }).prependTo(ul);
          }

          // Create initial inputs based on solected options
          $(select).find(":selected").each(function(index){
            var value = $(this).attr('value');
            $('<input>').attr({
              type: 'hidden',
              name: select_name,
              value: value,
            }).appendTo(form);
          });

          // Initialize Select2
          $(select).select2({
            containerCssClass: 'sortable-target',
          }).on('select2:select', function(e) {
            // Event for new selected option
            // - apends new hidden input
            $('<input>').attr({
                type: 'hidden',
                name: select_name,
                value: e.params.data.id,
              }).appendTo(form);
              do_sort_pills();
          }).on('select2:unselect', function(e) {
            // Event for deselected option
            // - removes hidden input
            $(form).find('input:hidden[name="' + select_name + '"][value="' + e.params.data.id + '"]').remove();
            do_sort_pills();
          });
          
          // Initialize jQuery UI sortable
          var ul = $('.sortable-target .select2-selection__rendered');
          $(ul).sortable({
              placeholder : 'ui-state-highlight',
              forcePlaceholderSize: true,
              items: '.select2-selection__choice:not(.select2-search--inline)',
              tolerance: 'pointer',
              create: function() {
                // Event fires when sortable is created
                do_sort_inputs(initial_sort);
                do_sort_pills();               
              },
              stop: function() {
                  // Event fires when sorting is over
                  do_sort_inputs();
                  do_sort_pills();
              }
          });
      }
  });
}(jQuery));

// Initialize select2 with sortable tags
jQuery(".select-multiple-sortable").select2_sortable();
```

**Comment by tanhaei** [comment]
I modified the code a little: (in my case I have titles but they differ from option values). I put the code here may be helpful for someone:

`$.fn.extend({
    select2_sortable: function () {
        var select = $(this);
        var select2dom = $(select).select2({
            width: "100%",
            createTag: function (params) {
                return undefined;
            }
        });
        var ul = $(select).next(".select2-container").find("ul.select2-selection__rendered");
        
        ul.sortable({
            placeholder: "ui-state-highlight",
            forcePlaceholderSize: true,
            items: "li:not(.select2-search__field)",
            tolerance: "pointer",
            stop: function () {
                $($(ul).find(".select2-selection__choice").get().reverse()).each(function () {
                    var selected = $(select).select2('data');
                    var title = $(this).attr('title');
                    var value = title;
                    for (var i = 0; i < selected.length; i++) {
                        if (selected[i].text == title) {
                            value = selected[i].id;
                        }
                    }
                    var option = $(select).find('option[value="' + value + '"]')[0];
                    $(select).prepend(option);
                });
            }
        });
    }
});`

**Comment by atipics** [comment]
Thanks a lot @tanhaei !!

**Comment by 21pratikpatel** [comment]
Hi guys, I have modified the code to create a new select element to store ordered option, since I am using multiple optgroups inside select. Here is my code, Hope it would help someone :)
`    $.fn.extend({
      select2_sortable: function(){
        var select = this;
        var select_alias = $(document.createElement('select')).prop({
                              name: 'ordered_'+$(this).attr('name')
                          }); 
        $(select).parent().append(select_alias);
        select_alias.hide();
        $(select).select2({
          width: "100%"
        });
        var ul = $(select).next('.select2-container').find('ul.select2-selection__rendered');
        ul.sortable({
          containment: 'parent',
          stop: function() {
              var option = [];
              var text ='';
              $(ul.find('.select2-selection__choice').get()).each(function() { 
                  var value = $(this).attr("title");
                  var selected = $(select).select2('data');
                  for (var i = 0; i < selected.length; i++) {
                      if (selected[i].title == value) {
                          value = selected[i].id;
                          text = selected[i].text;
                      }
                  }              
                  option.push('<option value="'+value+'">'+text+'</option>');
              });
              select_alias.empty().append(option);
          }
        });
      }
    });`

**Comment by 21pratikpatel** [comment]
Hi guys, I have modified the code to create a new multiple select element to store ordered options. Since I was using multiple optgroups inside select element, none of the above code worked for me. Here is my code for **Select2 [4.0.13]**, Hope it would help someone :)
<pre>
$.fn.extend({
  select2_sortable: function(){
    var select = this;
    var select_alias = $(document.createElement('select')).prop({
                          name: 'ordered_'+$(this).attr('name'),
                          multiple:'multiple'
                      }); 
    $(select).parent().append(select_alias);
    select_alias.hide();
    $(select).select2({
      width: "100%"
    });
    var ul = $(select).next('.select2-container').find('ul.select2-selection__rendered');
    ul.sortable({
      containment: 'parent',
      stop: function() {
          var option = [];
          var text ='';
          $(ul.find('.select2-selection__choice').get()).each(function() { 
              var value = $(this).attr("title");
              var selected = $(select).select2('data');
              for (var i = 0; i < selected.length; i++) {
                  if (selected[i].title == value) {
                      value = selected[i].id;
                      text = selected[i].text;
                  }
              }              
              option.push('&lt;option value="'+value +'" selected&gt;' +text+ '&lt;/option&gt;');
          });
          select_alias.empty().append(option);
      }
    });
  }
});
</pre>

**Comment by vahan889** [comment]
I'm using an ajax inside the select2 to search data from the DB to select. But with sortable select2 I can't implement an ajax. Anyone has a solution for that?
